import 'axis_grid.dart';

class XAxis extends GridAxis {
  const XAxis({
    super.alignTicks,
    super.position,
    super.type,
    super.offset,
    super.nameStyle,
    super.nameGap,
    super.nameAlign,
    super.inverse,
    super.min,
    super.max,
    super.start0,
    super.splitNumber,
    super.minInterval,
    super.maxInterval,
    super.interval,
    super.logBase,
    super.silent,
    super.axisLine,
    super.axisTick,
    super.minorTick,
    super.axisLabel,
    super.splitLine,
    super.minorSplitLine,
    super.splitArea,
    super.categoryList,
    super.axisPointer,
    super.name,
    super.show,
    super.formatFun,
    super.timeRange,
    super.timeSplitType,
  });
}
