import 'package:e_chart/e_chart.dart';

abstract class GridSeries<T extends StackItemData, G extends StackGroupData<T,G>> extends StackSeries<T, G> {
  GridSeries(
    super.data, {
    super.direction = Direction.vertical,
    super.dynamicRange,
    super.realtimeSort,
    super.dynamicLabel,
    super.selectedMode,
    super.animatorStyle,
    super.legendHoverLink,
    super.sort,
    super.sortCount,
    super.corner,
    super.cornerFun,
    super.columnGap,
    super.groupGap,
    super.innerGap,
    super.labelAlignFun,
    super.groupStyleFun,
    super.labelStyle,
    super.lineStyleFun,
    super.areaStyleFun,
    super.labelFormatFun,
    super.labelStyleFun,
    super.markLine,
    super.markPoint,
    super.markPointFun,
    super.markLineFun,
    super.animation,
    super.backgroundColor,
    super.clip,
    super.coordType,
    super.gridIndex,
    super.polarIndex,
    super.id,
    super.tooltip,
  });
}
